prepare_data <- function(){
  data_multiplex_aim2 <- read_excel(here::here("data/PCA_data.xlsx"), sheet="Aim 2 multiplex data")
  data_multiplex_aim2 <- deal_with_colnames(data_multiplex_aim2)
  unique(sapply(strsplit(names(data_multiplex_aim2), " "), function(x){x[3]}))
  data_multiplex_aim2$timepoint <- 2
  names(data_multiplex_aim2) <- gsub("seas. H5", "av. H5", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("seas. H7", "av. H7", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("seas. H9", "av. H9", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("av. HA", "av.", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pdm H1F-2009", "H1stem", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("seas. ", "s", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("vaxx ", "vaxx s", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pdm ", "p", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pN1-2009", "pN1", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pH1-2009", "pH1", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pM1-2009", "M1", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("pNP-2009", "NP", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("vaxx sH1-2007", "sH1", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("sH3-2007", "H3-2007", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2) <- gsub("sN1-2007", "N2-2007", names(data_multiplex_aim2), fixed=T)
  names(data_multiplex_aim2)

  data_multiplex_aim3 <- read_excel(here::here("data/PCA_data.xlsx"), sheet="Aim 3 multiplex data")
  data_multiplex_aim3 <- deal_with_colnames(data_multiplex_aim3)
  names(data_multiplex_aim3) <- gsub("H3N2/Victoria/2011", "H3-2011", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("Malaysia/2004", "HA-2004", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. H5", "av. H5", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. H7", "av. H7", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. H9", "av. H9", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("av. HA", "av.", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("pdm H1F-2009", "H1stem", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. H3F-1968", "H3stem", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. HA H5N1-2004", "av. H5-2004", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("HA H3", "seas. H3", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. B HA-2004", "seas. BVic-2004", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. B Bris HA-2008", "seas. BVic-2008", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("Bris H1-2007", "vaxx H1-2007", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("Bris H3-2007", "seas. H3-2007", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. B HA-2008", "sBVic-2008", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("seas. ", "s", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("vaxx ", "vaxx s", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3) <- gsub("pdm ", "p", names(data_multiplex_aim3), fixed=T)
  names(data_multiplex_aim3)

  split_tmp <- strsplit(data_multiplex_aim3$sample, "d", fixed=T)
  data_multiplex_aim3$sample <- sapply(split_tmp, function(x){x[1]})
  data_multiplex_aim3$sample <- gsub(" ", "", data_multiplex_aim3$sample, fixed=T)
  data_multiplex_aim3$group <- gsub(" ", "", data_multiplex_aim3$group, fixed=T)
  data_multiplex_aim3$timepoint <- sapply(split_tmp, function(x){as.numeric(x[2])})
  data_multiplex_aim3$timepoint[data_multiplex_aim3$group=="V0S0"] <- 2

  data_clinical_aim2 <- read_excel(here::here("data/PCA_data.xlsx"), sheet="Aim 2 clinical data")
  stopifnot(all(data_multiplex_aim2$sample %in% data_clinical_aim2$sample))
  data_clinical_aim3 <- read_excel(here::here("data/PCA_data.xlsx"), sheet="Aim 3 clinical data")
  stopifnot(all(data_multiplex_aim3$sample %in% data_clinical_aim3$sample))
  return(list(data_multiplex_aim2, data_clinical_aim2, data_multiplex_aim3, data_clinical_aim3))
}